"use client"

import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import type { TesterPerformanceResponse, TesterPerformanceRow } from "@shared/tester-performance"
import { MetricInfo } from "@frontend/components/insights/metric-info"
import { formatMinutes } from "@frontend/lib/workload-format"

const pct = (v: number | null, sample = true) => v == null || !sample ? "—" : `${v}%`
const boundedPct = (v: number | null, sample = true) => v == null || !sample ? "—" : `${Math.min(100, Math.max(0, v))}%`
const round1 = (v: number) => Math.round(v * 10) / 10
const title = (label: string, metric: Parameters<typeof MetricInfo>[0]["metric"]) => <h2 className="flex items-center gap-1.5 text-sm font-semibold text-foreground">{label}<MetricInfo metric={metric} /></h2>
const Panel = ({ children }: { children: React.ReactNode }) => <section className="min-w-0 overflow-hidden rounded-md border bg-card p-4">{children}</section>
// 모든 비율 지표는 동일하게 완료 작업 3건 이상일 때만 표시한다.
const sampleOk = (row: TesterPerformanceRow) => row.completed >= 3

export function ScheduleAdherenceSection({ data }: { data: TesterPerformanceResponse }) {
  const rows = data.byTester
  const charts = rows.map(r => {
    const eligible = r.overrunBuckets.compliant + r.overrunBuckets.oneDay + r.overrunBuckets.twoToThreeDays + r.overrunBuckets.fourPlusDays
    return { name: r.name, 공수: sampleOk(r) && eligible > 0 ? round1(r.overrunBuckets.compliant / eligible * 100) : null, 납기: sampleOk(r) ? r.dueComplianceRate : null }
  })
  const buckets = rows.map(r => ({ name: r.name, 준수: r.overrunBuckets.compliant, "+1일": r.overrunBuckets.oneDay, "+2~3일": r.overrunBuckets.twoToThreeDays, "+4일↑": r.overrunBuckets.fourPlusDays }))
  return <Panel><div className="flex items-center justify-between gap-2">{title("일정 준수와 지연", "dueCompliance")}<span className="text-xs text-muted-foreground">표본 3건 미만은 숨김</span></div><div className="mt-3 grid gap-4 lg:grid-cols-2"><div><p className="mb-2 flex items-center text-xs text-muted-foreground">납기·공수 준수율 (%)<MetricInfo metric="adherence" /></p><ResponsiveContainer width="100%" height={Math.max(170, rows.length * 34)}><BarChart data={charts} layout="vertical" margin={{ left: 5, right: 15 }}><CartesianGrid horizontal={false} stroke="var(--border)" /><XAxis type="number" domain={[0, 100]} /><YAxis type="category" dataKey="name" width={70} tick={{ fontSize: 13.5 }} /><Tooltip /><Legend /><Bar dataKey="납기" name="납기" fill="#2563eb" /><Bar dataKey="공수" name="공수 기준" fill="#93c5fd" /></BarChart></ResponsiveContainer></div><div><p className="mb-2 flex items-center text-xs text-muted-foreground">기준 초과일 버킷<MetricInfo metric="overrun" /></p><ResponsiveContainer width="100%" height={Math.max(170, rows.length * 34)}><BarChart data={buckets} layout="vertical" margin={{ left: 5, right: 15 }}><CartesianGrid horizontal={false} stroke="var(--border)" /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey="name" width={70} tick={{ fontSize: 13.5 }} /><Tooltip /><Legend /><Bar dataKey="준수" stackId="a" fill="#2563eb" /><Bar dataKey="+1일" stackId="a" fill="#f59e0b" /><Bar dataKey="+2~3일" stackId="a" fill="#fb923c" /><Bar dataKey="+4일↑" stackId="a" fill="#ef4444" /></BarChart></ResponsiveContainer></div></div><p className="mt-2 text-xs leading-normal text-muted-foreground">납기 준수율은 약속한 날짜, 공수 기준 준수율은 공수가 등록된 완료 작업 중 기준 이내 비율입니다. 둘을 합쳐 개인 순위로 해석하지 않습니다.</p></Panel>
}

export function DelayReasonSection({ data }: { data: TesterPerformanceResponse }) {
  const reasonData = data.delayReasons.map(r => ({ name: r.label, 건수: r.count, attribution: r.attribution }))
  const external = data.fairness.totalDelayJobs ? Math.round(data.fairness.externalDelayJobs / data.fairness.totalDelayJobs * 100) : null
  const byTesterReasons = data.byTester.map(row => ({ row, reasons: data.delaySpans.filter(span => span.testerId === row.testerId).reduce<Record<string, number>>((acc, span) => { const key = span.reasonCategoryName ?? "사유 미기록"; acc[key] = (acc[key] ?? 0) + 1; return acc }, {}) })).filter(item => Object.keys(item.reasons).length > 0)
  return <Panel><div className="flex items-center justify-between gap-2">{title("지연은 왜 났나", "delayReasons")}<span className="text-xs text-muted-foreground">통제 밖 / 통제 안 / 미기록</span></div>{reasonData.length === 0 ? <p className="py-8 text-center text-xs text-muted-foreground">기록된 지연이 없습니다.</p> : <div className="mt-3 grid items-center gap-4 md:grid-cols-[minmax(180px,240px)_1fr]"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={reasonData} dataKey="건수" nameKey="name" innerRadius={48} outerRadius={78}>{reasonData.map((r, i) => <Cell key={`${r.name}-${i}`} fill={r.attribution === "external" ? "#2563eb" : r.attribution === "internal" ? "#f59e0b" : "#94a3b8"} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="space-y-2">{reasonData.map(r => <div key={r.name} className="flex items-center justify-between gap-3 text-xs"><span className="truncate">{r.name}</span><span className="shrink-0 tabular-nums">{r.건수}건 · {r.attribution === "external" ? "통제 밖" : r.attribution === "internal" ? "통제 안" : "미기록"}</span></div>)}<p className="border-t pt-2 text-xs leading-normal text-muted-foreground"><span className="font-medium text-foreground">통제 밖 지연 비율</span><MetricInfo metric="externalDelay" /> {external == null ? "—" : `${external}%`} · 지연 작업 {data.fairness.totalDelayJobs}건</p><p className="text-xs leading-normal text-muted-foreground">선언된 지연 <span className="font-medium text-foreground">{data.byTester.reduce((n, r) => n + r.declaredDelayCount, 0)}건</span> · 자동 판정 <span className="font-medium text-foreground">{data.byTester.reduce((n, r) => n + r.autoOverdueCount, 0)}건</span></p><div className="border-t pt-2"><p className="mb-1 flex items-center text-xs font-medium text-foreground">시험자별 사유 분포<MetricInfo metric="delayReasons" /></p>{byTesterReasons.map(({ row, reasons }) => <p key={row.testerId} className="flex flex-wrap justify-between gap-2 text-xs"><span className="truncate">{row.name} · 납기 준수 {sampleOk(row) ? pct(row.dueComplianceRate) : "표본 부족"}</span><span className="shrink-0 tabular-nums">{Object.entries(reasons).map(([label, count]) => `${label} ${count}건`).join(" · ")}</span></p>)}</div></div></div>}<p className="mt-2 text-xs leading-normal text-muted-foreground">시험자별 행에 납기 준수율을 함께 표시해 지연 사유와 결과를 수동 대조하지 않아도 됩니다. 사유 미기록은 기능 도입 전 기록을 포함합니다.</p></Panel>
}

export function RecoverySection({ data }: { data: TesterPerformanceResponse }) {
  const rows = data.byTester.map(r => ({ name: r.name, 만회: sampleOk(r) && r.recoveryRate != null ? Math.min(100, r.recoveryRate) : null, 지연: r.delayJobs }))
  return <Panel><div className="flex items-center gap-1.5">{title("지연 후 만회", "recovery")}</div><p className="mt-1 text-xs leading-normal text-muted-foreground">지연된 작업 중 납기 안에 끝낸 결과를 보여줍니다. 지연만 세지 않고 따라잡은 작업도 같은 크기로 확인합니다.</p><p className="mt-1 text-xs leading-normal text-muted-foreground">현재 지연 중인 구간 <span className="font-medium text-foreground">{data.totals.ongoingDelayCount}건</span><MetricInfo metric="avgDelay" />은 별도로 표시합니다.</p><ResponsiveContainer width="100%" height={Math.max(170, rows.length * 34)}><BarChart data={rows} layout="vertical" margin={{ left: 5, right: 15 }}><CartesianGrid horizontal={false} stroke="var(--border)" /><XAxis type="number" domain={[0, 100]} /><YAxis type="category" dataKey="name" width={70} tick={{ fontSize: 13.5 }} /><Tooltip formatter={(v, n) => [n === "만회" ? boundedPct(v as number) : `${v}건`, n]} /><Bar dataKey="만회" fill="#2563eb" /></BarChart></ResponsiveContainer></Panel>
}

export function BalanceSection({ data }: { data: TesterPerformanceResponse }) {
  const rows = data.byTester.map(r => ({ ...r, sideToTestLabel: sampleOk(r) && r.sideToTestRatio != null ? `${r.sideToTestRatio}배` : "—", holiday: `${r.holidayItems}항목 · ${formatMinutes(r.holidayMinutes, "0분")}` }))
  return <Panel><div className="flex items-center gap-1.5">{title("일과 시간의 균형", "sideRatio")}</div><div className="mt-3 grid gap-2 sm:grid-cols-3">{rows.map(r => <div key={r.testerId} className="rounded-md border bg-muted/20 p-3"><p className="truncate text-xs font-medium">{r.name}</p><p className="mt-1 text-sm tabular-nums"><span className="font-semibold">{r.sideToTestLabel}</span> <span className="text-muted-foreground">부업무/시험</span><MetricInfo metric="sideToTest" /></p><p className="text-xs leading-normal text-muted-foreground">단편화 {sampleOk(r) && r.sideFragmentation != null ? `${r.sideFragmentation}건/일` : "기록 없음"}<MetricInfo metric="sideFragmentation" /> · 휴일 {r.holiday}<MetricInfo metric="holidayWork" /></p></div>)}</div><p className="mt-2 text-xs leading-normal text-muted-foreground">부업무가 주업무를 압도하는지와 휴일 흔적을 함께 봅니다. 휴일 완료는 실제 출근을 뜻하지 않습니다.</p></Panel>
}

export function ContextSection({ data }: { data: TesterPerformanceResponse }) {
  return <Panel><div className="flex items-center gap-1.5">{title("해석에 함께 볼 것", "availableUtilization")}</div><p className="mt-1 text-xs leading-normal text-muted-foreground">숫자를 사람에게 붙이기 전에 재배정·재실시·가용일을 확인하는 칸입니다.</p><div className="mt-3 overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-left text-muted-foreground"><th className="px-2 py-2">시험자</th><th className="px-2 py-2 text-right">가용일 보정<MetricInfo metric="availableUtilization" /></th><th className="px-2 py-2 text-right">재배정 받음/넘김<MetricInfo metric="reassignment" /></th><th className="px-2 py-2 text-right">재실시<MetricInfo metric="reopen" /></th><th className="px-2 py-2 text-right">동시분석 기여<MetricInfo metric="concurrent" /></th></tr></thead><tbody>{data.byTester.map(r => <tr key={r.testerId} className="border-b last:border-0"><td className="px-2 py-2 font-medium">{r.name}</td><td className="px-2 py-2 text-right tabular-nums">{pct(r.availableDayUtilization, sampleOk(r))}</td><td className="px-2 py-2 text-right tabular-nums">{r.reassignedIn}/{r.reassignedOut}</td><td className="px-2 py-2 text-right tabular-nums">{sampleOk(r) ? `${r.reopenCount}건` : "—"}</td><td className="px-2 py-2 text-right tabular-nums">{round1(r.concurrentSavingsDays)}일</td></tr>)}</tbody></table></div></Panel>
}
